### ISSUE TITLE
'_chsize' was not declared in this scope

### ISSUE THREAD

**Issue by robertaue** [rwinlib/base#11]
Hi

I am trying to install the matchingmarkets package from source (https://cran.r-project.org/web/packages/matchingMarkets/index.html) and get the following error:
```
In file included from C:/RBuildTools/3.5/mingw_64/x86_64-w64-mingw32/include/zconf.h:452:0,
                 from C:/RBuildTools/3.5/mingw_64/x86_64-w64-mingw32/include/zlib.h:34,
                 from ../inst/include/ParseUtils.h:27,
                 from ../inst/include/Options.h:30,
                 from Options.cc:21:
C:/RBuildTools/3.5/mingw_64/x86_64-w64-mingw32/include/unistd.h: In function 'int ftruncate(int, off32_t)':
C:/RBuildTools/3.5/mingw_64/x86_64-w64-mingw32/include/unistd.h:67:33: error: '_chsize' was not declared in this scope
   return _chsize (__fd, __length);
```
I found that the same error had occured here: http://r-forge.wu.ac.at/R/?group_id=1906&log=build_win64&pkg=matchingMarkets&flavor=patched. When I uncomment lines 65-68 of the header file unistd.h,
```
/*__CRT_INLINE int ftruncate(int __fd, off32_t __length)
{
  return _chsize (__fd, __length);
}*/
```
everything works well though. Does anyone have an idea why this is the case?

Thanks a lot!

**Comment by jeroen** [comment]
Why doesn't this error appear on CRAN?

It looks like a  name conflict. The header seems to get included via `zlib.h` via `Options.h` which is also including a bunch of other headers first. Likely one of these earlier headers defines something that disables or conflicts something in `zlib.h`.

**Comment by jeroen** [comment]
See -> https://github.com/r-windows/checks/issues/67
