### ISSUE TITLE
jrsoftware Inno Setup changed URL (broken link) today: 2019-04-27

### ISSUE THREAD

**Issue by AndreMikulec** [rwinlib/base#14]
@jeroen,

One may see the log of

https://ci.appveyor.com/project/AndreMikulec/base/build/job/m7ld9t20wp3hnwcf?fullLog=true

Error
```
Start-Process : This command cannot be run due to the error: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
At C:\projects\base\scripts\appveyor-tool.ps1:246 char:3
+   Start-Process -FilePath ..\innosetup.exe -ArgumentList /SILENT -NoN ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

Actual Error
Link: 
```
http://jrsoftware.org/download.php/is-unicode.exe?site=2
```
has changed to 

```
http://jrsoftware.org/download.php/is.exe?site=2
```

See the site:

http://jrsoftware.org/isdl.php

```
Change in default behavior: Starting with Inno Setup 6 there's only one version available: Unicode Inno Setup.

2019-04-27	Unicode Inno Setup self-installing package.

(new url)
http://jrsoftware.org/download.php/is.exe?site=2
```

Currrent URL of
base/scripts/appveyor-tool.ps1
https://github.com/rwinlib/base/blob/master/scripts/appveyor-tool.ps1

is

http://jrsoftware.org/download.php/is-unicode.exe?site=2

```
Error: Unknown filename specified
```

**Comment by AndreMikulec** [comment]
The new installer, hangs forever

See
https://ci.appveyor.com/project/AndreMikulec/base/build/job/880piuan4xoo1p8r


```
== 04/27/2019 17:16:05: Installig InnoSetup
DEBUG:   35+  >>>> }
DEBUG:  246+    >>>> Start-Process -FilePath ..\innosetup.exe -ArgumentList /SILENT -NoNewWindow -Wait
```

Looks like it will need the (new)? flag:  /ALLUSERS ( or /CURRENTUSER )

```
C:\Users\AnonymousUser\Downloads>innosetup-6.0.2.exe /ALLUSERS /SILENT 
```
works locally.

Also (/ALLUSERS), seems to install in

```
"C:\Program Files (x86)\Inno Setup 6"
```

**Comment by AndreMikulec** [comment]
Changed To
  
- appveyor-tool.ps1
  
  Progress "Installig InnoSetup"
  Start-Process -FilePath ..\innosetup.exe  -NoNewWindow -Wait -ArgumentList /ALLUSERS,/SILENT

  Progress "InnoSetup installation: Done"
  Get-ItemProperty "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
  
- MkRules.local.in

  ISDIR = C:/Program Files (x86)/Inno Setup 6
  
So far, this seems to be working ...

https://ci.appveyor.com/project/AndreMikulec/base/build/job/tgrjer918fytxlru

**Comment by AndreMikulec** [comment]
Old 5 works here
https://ci.appveyor.com/project/AndreMikulec/base/builds/22977434/job/fxly09urb6g0j3wb?fullLog=true

```
../../../bin/x64/Rscript JRins.R \
  R-3.5.3 R-3.5.3 0 \
  1 R-core "C:/Program Files (x86)/Inno Setup 5"
"C:/Program Files (x86)/Inno Setup 5/iscc" R.iss > R-3.5.3.log 2>&1
```


New 6 dies here
https://ci.appveyor.com/project/AndreMikulec/base/build/job/tgrjer918fytxlru?fullLog=true
```
../../../bin/x64/Rscript JRins.R \
  R-3.6.0 R-3.6.0 0 \
  1 R-core "C:/Program Files (x86)/Inno Setup 6"
"C:/Program Files (x86)/Inno Setup 6/iscc" R.iss > R-3.6.0.log 2>&1
make[2]: *** [Makefile:175: R-3.6.0-win.exe] Error 2
make[1]: *** [Makefile:387: rinstaller] Error 2
make: *** [Makefile:401: distribution] Error 2
```
InnoSetup is "beyond my skill."  Maybe an InnoSetup expert knows.

**Comment by AndreMikulec** [comment]
But then I noticed that this job using the old software link URL from seven(7) hours ago

$inno_url = "http://jrsoftware.org/download.php/is.exe?site=2"

*did* build 7 hours ago

https://ci.appveyor.com/project/AndreMikulec/base/builds/24144511/job/m7ld9t20wp3hnwcf?fullLog=true

with this error(that did not seem to affect the build)
```
Start-Process : This command cannot be run due to the error: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
At C:\projects\base\scripts\appveyor-tool.ps1:246 char:3
+   Start-Process -FilePath ..\innosetup.exe -ArgumentList /SILENT -NoN ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
``` 
and still created
https://github.com/AndreMikulec/base/releases

https://github.com/AndreMikulec/base/releases/download/base_0.1.0-46-master_r-patched_R-3.6.0_R-3.6.0_CoreI7_mAVX2_NoDebug.zip/base_0.1.0-46-master_r-patched_R-3.6.0_R-3.6.0_CoreI7_mAVX2_NoDebug.zip

Using commit "miktex from 7021 to 7031"
Therefore, at that commit, I am running the other build job  (that I had previously cancelled) 
that builds the "Generic_Debug" R variant. (Maybe the build job will work?)

https://ci.appveyor.com/project/AndreMikulec/base/build/job/grwyh6kq48ciojf7

**Comment by AndreMikulec** [comment]
O.K.
So, this build-job (above) works
https://ci.appveyor.com/project/AndreMikulec/base/build/job/grwyh6kq48ciojf7

Still, it produced this (obviously non-fatal) error.
```
Start-Process : This command cannot be run due to the error: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
At C:\projects\base\scripts\appveyor-tool.ps1:246 char:3
+   Start-Process -FilePath ..\innosetup.exe -ArgumentList /SILENT -NoN ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
 
DEBUG:  248+    >>>> Progress "InnoSetup installation: Done"
```

The release produced (as wished-for).

https://github.com/AndreMikulec/base/releases/download/base_0.1.0-46-master_r-patched_R-3.6.0_R-3.6.0_Generic_Debug.zip/base_0.1.0-46-master_r-patched_R-3.6.0_R-3.6.0_Generic_Debug.zip

So, I do not know what the "deal is about that (obviously non-fatal) error."

**Comment by jeroen** [comment]
Thanks for investigating! I guess we need to roll back to Inno5 until we figure out what is going on.

@martijnlaan

**Comment by AndreMikulec** [comment]
A note . . .
```
From: R-devel <r-devel-bounces@r-project.org> on behalf of Avraham Adler <avraham.adler@gmail.com>
Sent: Sunday, April 28, 2019 5:06 AM
To: R-devel
Subject: [Rd] Inno Setup 6.0.2 fails before creating exe file on Windows (R-3.6.0)
 
I am working on compiling R-3.6.0 for Windows 10 64bit using rtools40
(beta 11). I had also installed the most recent update of Inno setup,
which is now 6.0.2.With that version, `make risntaller` fails at the
call to ""C:/R/Inno/iscc" R.iss > R-3.6.0.log 2>&1" and just exits,
pointing to line 175 of the makefile which is:

$(RPREFIX)-win.exe: R.iss
    "$(ISDIR)/iscc" R.iss > $(RPREFIX).log 2>&1

Reinstalling Inno Setup 5.6.1 does allow the exe file to be created.

Thank you,

Avi
```

**Comment by AndreMikulec** [comment]
jeroen,
```
Thanks for investigating! I guess we need to roll back to Inno5 until we figure out what is going on.
```
I meant to say: staying on Inno5 is sufficient.  Link http://jrsoftware.org/download.php/is-unicode.exe?site=2 seems to *not work* in an interactive web browser, but it(the link) does (still) allow downloading the Inno 5 install.exe.

However, in the install of Inno5, `Set-PSDebug -Trace 2` shows some unhappiness. 

Also, Inno6 does not seem to work  (yet).

**Comment by jeroen** [comment]
Right but it would be nice to figure out why Inno6 is not working. I suspect there is a hint in the iscc log:

```
"C:/Program Files (x86)/Inno Setup 5/iscc" R.iss > R-3.5.3.log 
```

**Comment by AndreMikulec** [comment]
@jeroen 

OK. Inno6 works.  

https://github.com/AndreMikulec/base/blob/master/appveyor.yml
      innosetup: 6

https://ci.appveyor.com/project/AndreMikulec/base/builds/24307722
https://github.com/AndreMikulec/base/releases

This ticket can be closed.  

Thanks, for the help.
