### ISSUE TITLE
Small thing to add to the README

### ISSUE THREAD

**Issue by gaborcsardi** [rwinlib/base#16]
A `patch.exe` is also needed if you have any patches. I am not sure about the best way to install it, though....

**Comment by jeroen** [comment]
It should be in rtools.

**Comment by gaborcsardi** [comment]
Was not there for me, maybe I had an old version of rtools...

**Comment by jeroen** [comment]
I added it in rtools35 a year ago or so.

**Comment by gaborcsardi** [comment]
Yeah, I guess I had an older version then....
