### ISSUE TITLE
expired digital certificate of ftp.opencpu.org

### ISSUE THREAD

**Issue by AndreMikulec** [rwinlib/base#18]
The digital certificate of the web site https://ftp.opencpu.org/ has expired.

**Comment by jeroen** [comment]
Thanks, should be fixed now!

Note to self: to manually renew cert, run `sudo letsencrypt` on the server. Also added root cronjob:

```
0 0 1 * * /usr/bin/certbot renew
```

Which should renew (when due) on the first if each month.
