### ISSUE TITLE
Question about installation of Rtools

### ISSUE THREAD

**Issue by robertdj** [rwinlib/base#22]
Hi

In the build script <https://github.com/rwinlib/base/blob/master/scripts/appveyor-tool.ps1> Rtools is installed with the command 

```
Rtools-current.exe -ArgumentList "/TYPE=full /VERYSILENT" -NoNewWindow -Wait
```

The graphical installer looks like this:
![image](https://user-images.githubusercontent.com/5703657/70437275-80afc280-1a8b-11ea-9d6d-0d7faee88ff7.png)

Do you know where to find the valid `/TYPE` arguments? 
Or alternatively what `/TYPE` should be to get only "Tools for building R packages from source"?

**Comment by jeroen** [comment]
I think that is the default if you don't specify any type?

**Comment by robertdj** [comment]
I hadn't considered to try without `/TYPE`, but it does install enough to compile packages :-) 
Thanks!
