### ISSUE TITLE
Rtools 3.4 compatibility with R 3.6.2

### ISSUE THREAD

**Issue by brianstamper** [rwinlib/base#23]
According to this page: https://cran.r-project.org/bin/windows/Rtools/index.html
Rtools 3.4 should be fine with R 3.3 and up, but I'm getting this message:

> WARNING: Rtools is required to build R packages but no version of Rtools compatible with the currently running version of R was found. Note that the following incompatible version(s) of Rtools were found:
> 
>   \- Rtools 3.4 (installed at C:\RBuildTools\3.4)

These two messages seem to be at odds - which is correct, do I need Rtools 3.5? My computer is controlled by my employer and I'm trying to keep additional software update requests minimal, otherwise I would just upgrade to 3.5 myself.

More generally speaking, should we be trying to always keep Rtools up to date with the most recent (non-experimental) version? Or as long as it still works it is ok? To be clear we don't do any serious package building, this is just to support package installs.

Thanks!

**Comment by jeroen** [comment]
You are correct, Rtools 3.4 is fine for R 3.3 and up. Where do you see this message? I think it may be a bug in rstudio or devtools?

**Comment by jeroen** [comment]
You are correct, Rtools 3.4 is fine for R 3.3 and up. Where do you see this message? I think it may be a bug in devtools. Can you please open an issue here (and preferably include the code you run): https://github.com/r-lib/pkgbuild

**Comment by brianstamper** [comment]
New issue filed here: https://github.com/r-lib/pkgbuild/issues/90
