### ISSUE TITLE
gcc -O flag differs between i386 and x64

### ISSUE THREAD

**Issue by jangorecki** [rwinlib/base#27]
Hi @jeroen 
I am trying to setup my windows build environment on new GitLab Windows Shared CI runners (it is the same on appveyor), and I spotted this:
```
** libs
*** arch - i386
 c:/Rtools/mingw_32/bin/gcc  -I"C:/R/include" -DNDEBUG       -fopenmp   -O3 -Wall  -std=gnu99 -mtune=core2 -c assign.c -o assign.o
...
*** arch - x64
 c:/Rtools/mingw_64/bin/gcc  -I"C:/R/include" -DNDEBUG       -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c assign.c -o assign.o
...
```
Everything looks quite the same, except the `-O` flag.
For i386 it is `-O3`, and for x64 it is `-O2`.

Is it expected configuration? Shouldn't that be aligned to use same optimization level?
Is it safe to put `~/.R/Makevars` (or its Windows equivalent) compilation flags `-O3`, or it is better to avoid doing so for the sake of portability?

Doesn't seem to be related but `src/Makevars`:
```

PKG_CFLAGS = $(SHLIB_OPENMP_CFLAGS)
PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) -lz

all: $(SHLIB)
	mv $(SHLIB) datatable$(SHLIB_EXT)
	if [ "$(OS)" != "Windows_NT" ] && [ `uname -s` = 'Darwin' ]; then install_name_tool -id datatable$(SHLIB_EXT) datatable$(SHLIB_EXT); fi

```
Thank you

**Comment by jeroen** [comment]
That's indeed how R 3.3 - 3.6 was configured. In R 4.0 we switched it to compile everything with o2. It really doesn't matter much, except for some edge cases in numeric precision.

**Comment by jangorecki** [comment]
@jeroen Thank you!
