### ISSUE TITLE
Request to automatically set BINPREF when Rtools is installed in a custom location

### ISSUE THREAD

**Issue by JoFAM** [rwinlib/base#8]
As @jeroen mentioned here : https://twitter.com/opencpu/status/982202170094178304

setting the BINPREF environment variable is necessary to build eg Rcpp when Rtools is installed in a different location than c:\Rtools. It would be nice to have at least the option in the installer to set this environment variable.

EDIT: I realized I put this in the Windows R build repo itself. Is there one for issues with Rtools or is this the correct location?

**Comment by jeroen** [comment]
This repo is indeed for the base R installer. The repo for rtools is: https://github.com/rwinlib/rtools35

**Comment by JoFAM** [comment]
Thx and sorry. New issue here : https://github.com/rwinlib/rtools35/issues/2
