### ISSUE TITLE
ALTREP header file missing in R 3.5.0 binary distribution

### ISSUE THREAD

**Issue by MarcusKlik** [rwinlib/base#9]
Thanks @jeroen for all the great work on providing the windows (development) build and toolchain!

I have a question on the `ALTREP` framework that is now part of `R 3.5.0`. If you feel this is the wrong place for that, please let me know. I'm trying to build a new package that provides custom `ALTREP` vectors. For that, the [R_ext/Altrep.h](https://github.com/wch/r-source/blob/trunk/src/include/R_ext/Altrep.h) header needs to be included in the package `C++` source (that's where the _ALTREP interface_ is defined).

I noticed that this header file is missing from the `R` Windows distributions, both in `3.5.0` and the `dev` versions. When I manually include the header from the `R` source code, I (logically) get a series of undefined references to the methods defined in _Altrep.h_.

This prevents building custom `ALTREP` implementations with the Windows toolchain. From the [`ALTREP` documentation](https://svn.r-project.org/R/branches/ALTREP/ALTREP.html) (referenced in the [release notes](https://cran.r-project.org/bin/windows/base/NEWS.R-3.5.0.html) for R 3.5.0) it looks like custom package creation should be possible with `R 3.5.0`. This is also suggested by the reference to the [simplemmap](https://github.com/ltierney/Rpkg-simplemmap) package, which can't be build on Windows at the moment, due to the issue mentioned above (and others).

Do you know anything about the roadmap for exporting the `ALTREP` interface for use in custom packages? Thanks a lot!

**Comment by jeroen** [comment]
Thanks for reporting! This looks like a bug in the script that creates the installer.

I think we need to explicitly add `Altrep.h` to the headers that ship with the windows distribution as specified [here](https://github.com/wch/r-source/blob/4686cdd38aa85d66da2918365c9662239299ed74/src/include/Makefile.win#L15-L23).

**Comment by jeroen** [comment]
I think we forgot to explicitly add `Altrep.h` to the headers that ship with the windows distribution: https://github.com/wch/r-source/blob/4686cdd38aa85d66da2918365c9662239299ed74/src/include/Makefile.win#L15-L23

**Comment by MarcusKlik** [comment]
Thanks for checking that! It would be nice to have access to the `ALTREP` internals and without it, packages that are build from source will probably have problems on Windows later on.

**Comment by jeroen** [comment]
Yes that is definitely the intention, thanks for catching this :)

**Comment by jeroen** [comment]
OK they [fixed](https://github.com/wch/r-source/commit/14b7ec2b2c6d299f8bc3f6266372208708ae2e31) it in base R. It should be there starting tomorrow in the daily R-patched and R-devel builds.

**Comment by MarcusKlik** [comment]
Great, thanks! I will let you know if the package (with custom `ALTREP` vectors) can be build successfully on Windows once the R-devel build is there!

**Comment by jeroen** [comment]
Did you get a chance to test this?
